# push時にyarn format を実行する
name: code-format
on: [push]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.17.1

      - name: Install Yarn
        run: npm i -g yarn

      - run: yarn
      - run: yarn format
